import {
  Sparkles,
  Palmtree,
  TrendingUp,
  TrendingDown,
  HeartCrack,
  Rocket,
  Clock,
  BookOpen,
  CalendarDays,
  Package,
  Target,
  Wallet,
  ClipboardList,
  Receipt,
  Landmark,
  MailOpen,
  Search,
  CircleX,
  CircleCheck,
  CircleMinus,
  CircleAlert,
  LifeBuoy,
  Gauge,
  RefreshCw,
  Plus,
  UserPlus,
  AlertTriangle,
  Settings,
  Lightbulb,
  Shield,
  type LucideProps,
} from "lucide-react";
import { type ComponentType } from "react";

const ICON_MAP: Record<string, ComponentType<LucideProps>> = {
  sparkles: Sparkles,
  palmtree: Palmtree,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "heart-crack": HeartCrack,
  rocket: Rocket,
  clock: Clock,
  "book-open": BookOpen,
  calendar: CalendarDays,
  package: Package,
  target: Target,
  wallet: Wallet,
  clipboard: ClipboardList,
  receipt: Receipt,
  landmark: Landmark,
  "mail-open": MailOpen,
  search: Search,
  "circle-x": CircleX,
  "circle-check": CircleCheck,
  "circle-minus": CircleMinus,
  "circle-alert": CircleAlert,
  "life-buoy": LifeBuoy,
  gauge: Gauge,
  "refresh-cw": RefreshCw,
  plus: Plus,
  "user-plus": UserPlus,
  "alert-triangle": AlertTriangle,
  settings: Settings,
  lightbulb: Lightbulb,
  shield: Shield,
};

interface IconProps extends LucideProps {
  name: string;
}

export function Icon({ name, ...props }: IconProps) {
  const IconComponent = ICON_MAP[name];
  if (!IconComponent) return null;
  return <IconComponent {...props} />;
}

export {
  Sparkles,
  Palmtree,
  TrendingUp,
  TrendingDown,
  HeartCrack,
  Rocket,
  Clock,
  BookOpen,
  CalendarDays,
  Package,
  Target,
  Wallet,
  ClipboardList,
  Receipt,
  Landmark,
  MailOpen,
  Search,
  CircleX,
  CircleCheck,
  CircleMinus,
  CircleAlert,
  LifeBuoy,
  Gauge,
  RefreshCw,
  Plus,
  UserPlus,
  AlertTriangle,
  Settings,
  Lightbulb,
  Shield,
};
